-- Insert test cases from user-provided list
INSERT INTO test_cases (hang_muc, tinh_nang, mo_ta, so_lan_phai_test, created_at) VALUES
('App - Đăng Ký', 'Đăng ký thành công với trường bắt buộc', 'Đăng ký tài khoản với các trường bắt buộc (Họ tên, Số điện thoại, Email), hiển thị thông báo "Tài khoản đăng ký thành công".', 10, NOW()),
('App - Đăng Ký', 'Kiểm tra xác thực dữ liệu trống', 'Nhấn nút "Đăng ký" mà không nhập dữ liệu, hiển thị thông báo "Bắt buộc" màu đỏ.', 10, NOW()),
('App - Đăng Ký', 'Đăng ký không thành công với số điện thoại không hợp lệ', 'Đăng ký với số điện thoại vượt quá 12 số hoặc chứa khoảng trắng, hiển thị thông báo "Không hợp lệ" màu đỏ.', 10, NOW()),
('App - Đăng Ký', 'Đăng ký Affiliate không thành công với mã giới thiệu không hợp lệ', 'Nhập mã giới thiệu dưới 6 ký tự, hiển thị thông báo "Mã giới thiệu không hợp lệ" màu đỏ.', 10, NOW()),
('App - Đăng Ký', 'Đăng ký Affiliate thành công với mã giới thiệu hợp lệ', 'Nhập mã giới thiệu hợp lệ (tối thiểu 6 ký tự, không khoảng trắng), hiển thị thông báo "Tài khoản đăng ký thành công".', 10, NOW()),
('App - Đăng Ký', 'Xác nhận email cho người tạo tài khoản', 'Sau khi đăng ký thành công, email xác nhận được gửi tới người tạo tài khoản.', 10, NOW()),
('App - Đăng Ký', 'Xác nhận email cho người giới thiệu', 'Khi khách hàng đăng ký với mã giới thiệu, email xác nhận được gửi tới người giới thiệu.', 10, NOW()),
('App - Đăng Nhập', 'Đăng nhập thành công với trường bắt buộc', 'Đăng nhập với Email/Số điện thoại và Mật khẩu hợp lệ, hiển thị thông báo "Đăng nhập thành công".', 10, NOW()),
('App - Đăng Nhập', 'Kiểm tra xác thực dữ liệu trống', 'Nhấn nút "Đăng nhập" mà không nhập dữ liệu, hiển thị thông báo "Bắt buộc" màu đỏ.', 10, NOW()),
('App - Đăng Nhập', 'Đăng nhập không thành công với Email/Số điện thoại không có giá trị', 'Đăng nhập với Email/Số điện thoại trống, hiển thị thông báo "Không hợp lệ" màu đỏ.', 10, NOW()),
('App - Đăng Nhập', 'Đăng nhập không thành công với mật khẩu không có giá trị', 'Đăng nhập với Email/Số điện thoại hợp lệ nhưng mật khẩu trống, hiển thị thông báo "Không hợp lệ" màu đỏ.', 10, NOW()),
('App - Quên Mật Khẩu', 'Lấy mã OTP không thành công với Email trống', 'Nhấn "Lấy mã xác minh" với Email trống, hiển thị thông báo "Vui lòng điền Email" màu đỏ.', 10, NOW()),
('App - Quên Mật Khẩu', 'Đặt lại mật khẩu với Email chưa đăng ký', 'Nhập Email đúng định dạng nhưng chưa tồn tại, hiển thị thông báo "Email chưa đăng ký tài khoản".', 10, NOW()),
('App - Quên Mật Khẩu', 'Đặt lại mật khẩu với Email không hợp lệ', 'Nhập Email không đúng định dạng, hiển thị thông báo "Vui lòng nhập email đúng định dạng" màu đỏ.', 10, NOW()),
('App - Quên Mật Khẩu', 'Nhập mã xác nhận sau thời gian hết hạn', 'Nhập mã xác nhận sau 120s, hiển thị thông báo "Mã không hợp lệ hoặc đã hết hạn" màu đỏ.', 10, NOW()),
('App - Quên Mật Khẩu', 'Nhập mã xác minh không khớp', 'Nhập mã xác minh sai, hiển thị thông báo "Mã không hợp lệ hoặc đã hết hạn" màu đỏ.', 10, NOW()),
('App - Quên Mật Khẩu', 'Đặt lại mật khẩu thành công', 'Đặt lại mật khẩu với Email, mã xác minh hợp lệ và mật khẩu trùng khớp, hiển thị thông báo "Mật khẩu của bạn đã được thay đổi thành công".', 10, NOW()),
('App - Quên Mật Khẩu', 'Đặt lại mật khẩu không thành công với mật khẩu không trùng khớp', 'Nhập mật khẩu và xác nhận mật khẩu không khớp, hiển thị thông báo "Mật khẩu không trùng khớp" màu đỏ.', 10, NOW()),
('App - Quên Mật Khẩu', 'Kiểm tra xác thực trống', 'Nhấn "Xác nhận" mà không nhập dữ liệu, hiển thị thông báo "Bắt buộc" màu đỏ.', 10, NOW()),
('App - Quên Mật Khẩu', 'Đặt lại mật khẩu không thành công với mật khẩu không đúng định dạng', 'Nhập mật khẩu chứa khoảng trắng, hiển thị thông báo "Mật khẩu không đúng định dạng" màu đỏ.', 10, NOW()),
('App - Tạo Phiếu Nạp Tiền', 'Tạo phiếu nạp tiền mặt thành công', 'Tạo phiếu nạp với số tiền hợp lệ, hiển thị thông báo thành công và phiếu ở trạng thái "Chờ Duyệt".', 10, NOW()),
('App - Tạo Phiếu Nạp Tiền', 'Tạo phiếu nạp tiền mặt không thành công', 'Tạo phiếu nạp với số tiền nhỏ hơn tối thiểu, hiển thị thông báo "Số tiền nạp tối thiểu".', 10, NOW()),
('App - Tạo Phiếu Nạp Tiền', 'Tạo phiếu nạp chuyển khoản thành công', 'Tạo phiếu nạp với số tiền và ảnh chứng từ hợp lệ, hiển thị thông báo thành công và phiếu ở trạng thái "Chờ Duyệt".', 10, NOW()),
('App - Tạo Phiếu Nạp Tiền', 'Tạo phiếu nạp chuyển khoản không thành công', 'Tạo phiếu nạp với số tiền nhỏ hơn tối thiểu, hiển thị thông báo "Số tiền nạp tối thiểu".', 10, NOW()),
('App - Tạo Phiếu Nạp Tiền', 'Tạo phiếu nạp chuyển khoản không thành công khi thiếu ảnh chứng từ', 'Tạo phiếu nạp mà không đính kèm ảnh chứng từ, phiếu không được nộp.', 10, NOW()),
('App - Tạo Phiếu Nạp Tiền', 'Kiểm tra xác thực trống', 'Nhấn "Nạp tiền" mà không nhập số tiền, hiển thị thông báo "Vui lòng nhập số tiền cần nạp".', 10, NOW()),
('App - Tạo Phiếu Nạp Tiền', 'Kiểm tra lịch sử nạp/rút tiền', 'Xem danh sách giao dịch nạp/rút theo trạng thái (chờ duyệt, thành công, thất bại).', 10, NOW()),
('App - Tạo Phiếu Rút Tiền', 'Tạo phiếu rút tiền mặt thành công', 'Tạo phiếu rút với số tiền hợp lệ, hiển thị thông báo thành công và phiếu ở trạng thái "Chờ Duyệt".', 10, NOW()),
('App - Tạo Phiếu Rút Tiền', 'Tạo phiếu rút tiền mặt không thành công với số tiền nhỏ hơn tối thiểu', 'Tạo phiếu rút với số tiền nhỏ hơn tối thiểu, hiển thị thông báo "Số tiền rút tối thiểu".', 10, NOW()),
('App - Tạo Phiếu Rút Tiền', 'Tạo phiếu rút tiền mặt không thành công với số tiền vượt tối đa', 'Tạo phiếu rút với số tiền lớn hơn tối đa, hiển thị thông báo "Số tiền rút tối đa".', 10, NOW()),
('App - Tạo Phiếu Rút Tiền', 'Tạo phiếu rút chuyển khoản thành công', 'Tạo phiếu rút với số tiền và số tài khoản hợp lệ, hiển thị thông báo thành công và phiếu ở trạng thái "Chờ Duyệt".', 10, NOW()),
('App - Tạo Phiếu Rút Tiền', 'Tạo phiếu rút chuyển khoản không thành công', 'Tạo phiếu rút với số tiền không hợp lệ, hiển thị thông báo "Số tiền rút tối thiểu/tối đa".', 10, NOW()),
('App - Tạo Phiếu Rút Tiền', 'Tạo phiếu rút chuyển khoản không thành công khi thiếu số tài khoản', 'Tạo phiếu rút mà không chọn số tài khoản, phiếu không được nộp.', 10, NOW()),
('App - Tạo Phiếu Rút Tiền', 'Kiểm tra xác thực trống', 'Nhấn "Rút tiền" mà không nhập số tiền, hiển thị thông báo "Vui lòng nhập số tiền cần rút".', 10, NOW()),
('App - Phương Thức Thanh Toán', 'Thêm phương thức thanh toán thành công', 'Thêm mới phương thức thanh toán với thông tin hợp lệ, hiển thị thông báo "Thêm tài khoản thành công".', 10, NOW()),
('App - Phương Thức Thanh Toán', 'Kiểm tra xác thực trống', 'Nhấn "Lưu" mà không nhập dữ liệu, hiển thị thông báo yêu cầu nhập thông tin.', 10, NOW()),
('App - Phương Thức Thanh Toán', 'Thêm phương thức thanh toán không thành công với tên chủ tài khoản dưới 2 ký tự', 'Nhập tên chủ tài khoản dưới 2 ký tự, hiển thị thông báo "Tối thiểu 2 ký tự".', 10, NOW()),
('App - Phương Thức Thanh Toán', 'Thêm phương thức thanh toán không thành công với số tài khoản dưới 6 ký tự', 'Nhập số tài khoản dưới 6 ký tự, hiển thị thông báo "Tối thiểu 6 ký tự".', 10, NOW()),
('App - Phương Thức Thanh Toán', 'Chỉnh sửa tài khoản ngân hàng thành công', 'Cập nhật thông tin tài khoản ngân hàng, hiển thị thông báo "Cập nhật tài khoản thành công".', 10, NOW()),
('App - Phương Thức Thanh Toán', 'Xóa tài khoản ngân hàng thành công', 'Xóa tài khoản ngân hàng, hiển thị thông báo "Xóa tài khoản thành công".', 10, NOW()),
('App - Cửa Hàng', 'Đăng ký mở cửa hàng thành công với trạng thái "Chờ bổ sung hồ sơ"', 'Đăng ký cửa hàng với thông tin hợp lệ, hiển thị thông báo "Đăng ký thành công" và trạng thái "Chờ bổ sung hồ sơ".', 10, NOW()),
('App - Cửa Hàng', 'Đăng ký mở cửa hàng thành công với trạng thái "Chờ duyệt"', 'Đăng ký cửa hàng với thông tin và giấy phép hợp lệ, hiển thị thông báo "Đăng ký thành công" và trạng thái "Chờ duyệt".', 10, NOW()),
('App - Cửa Hàng', 'Kiểm tra xác thực trống thông tin cửa hàng', 'Nhấn "Tiếp tục" mà không nhập thông tin cửa hàng, hiển thị thông báo "Không được để trống".', 10, NOW()),
('App - Cửa Hàng', 'Chỉnh sửa thông tin cửa hàng thành công', 'Cập nhật thông tin cửa hàng, hiển thị thông báo "Cập nhật cửa hàng thành công" và đợi phê duyệt.', 10, NOW()),
('App - Cửa Hàng', 'Bổ sung hồ sơ thành công cho cửa hàng "Chờ bổ sung hồ sơ"', 'Thêm hồ sơ cho cửa hàng, chuyển trạng thái sang "Chờ duyệt" sau khi lưu.', 10, NOW()),
('App - Cửa Hàng', 'Cập nhật thông tin liên hệ cửa hàng thành công', 'Cập nhật thông tin liên hệ (ngành hàng, địa điểm), hiển thị thông báo "Cập nhật thông tin cửa hàng thành công".', 10, NOW()),
('App - Cửa Hàng', 'Yêu cầu chỉnh sửa thông tin liên hệ cửa hàng thành công', 'Gửi yêu cầu chỉnh sửa thông tin (ảnh đại diện, banner, tên cửa hàng, giới thiệu), hiển thị thông báo "Cập nhật cửa hàng thành công".', 10, NOW()),
('App - Sản Phẩm', 'Thêm sản phẩm mới thành công', 'Thêm sản phẩm mới với thông tin hợp lệ, hiển thị thông báo "Tạo sản phẩm mới thành công".', 10, NOW()),
('App - Sản Phẩm', 'Kiểm tra xác thực trống', 'Nhấn "Lưu" mà không nhập thông tin sản phẩm, hiển thị thông báo "Không được để trống".', 10, NOW()),
('App - Sản Phẩm', 'Thêm sản phẩm không thành công khi thiếu phân loại hàng', 'Thêm sản phẩm mà không điền phân loại hàng, hiển thị thông báo yêu cầu thêm phân loại hàng.', 10, NOW()),
('App - Sản Phẩm', 'Chỉnh sửa sản phẩm thành công', 'Cập nhật thông tin sản phẩm, hiển thị thông báo "Cập nhật thông tin sản phẩm thành công".', 10, NOW()),
('App - Sản Phẩm', 'Ẩn sản phẩm thành công', 'Ẩn sản phẩm, chuyển trạng thái sang "Không hoạt động".', 10, NOW()),
('App - Sản Phẩm', 'Mở sản phẩm thành công', 'Mở sản phẩm, chuyển trạng thái sang "Hoạt động".', 10, NOW()),
('App - Sản Phẩm', 'Hiển thị chi tiết sản phẩm', 'Xem chi tiết sản phẩm, hiển thị đầy đủ thông tin sản phẩm.', 10, NOW()),
('App - Đặt Sản Phẩm', 'Đặt hàng thành công thanh toán bằng ví', 'Đặt hàng và thanh toán bằng ví, hiển thị thông báo "Đặt hàng thành công" và trừ tiền trong ví.', 10, NOW()),
('App - Đặt Sản Phẩm', 'Đặt hàng không thành công với số lượng bằng 0', 'Đặt hàng với số lượng 0, hiển thị thông báo yêu cầu nhập số lượng lớn hơn 1.', 10, NOW()),
('App - Đặt Sản Phẩm', 'Đặt hàng thành công thanh toán bằng tiền mặt/chuyển khoản', 'Đặt hàng với phương thức thanh toán tiền mặt/chuyển khoản, hiển thị thông báo "Đặt hàng thành công".', 10, NOW()),
('App - Đặt Sản Phẩm', 'Thêm sản phẩm vào giỏ hàng thành công', 'Thêm sản phẩm vào giỏ hàng, hiển thị thông báo "Thêm giỏ hàng thành công" và sản phẩm xuất hiện trong giỏ.', 10, NOW()),
('App - Đặt Sản Phẩm', 'Quét QR cửa hàng thanh toán thành công', 'Quét QR hợp lệ và thanh toán, hiển thị thông báo "Thanh toán thành công" và trừ tiền trong ví.', 10, NOW()),
('App - Đặt Sản Phẩm', 'Quét QR cửa hàng thanh toán không thành công', 'Quét QR không hợp lệ, hiển thị thông báo "QR không hợp lệ".', 10, NOW()),
('App - Đặt Sản Phẩm', 'Kiểm tra lịch sử giao dịch', 'Xem danh sách lịch sử giao dịch, hiển thị đầy đủ các giao dịch.', 10, NOW()),
('App - Đặt Sản Phẩm', 'Gửi email xác nhận đơn hàng', 'Sau khi đặt hàng, email xác nhận được gửi tới người đặt.', 10, NOW()),
('App - Đặt Sản Phẩm', 'Xác nhận lịch sử Affiliate khi hoàn thành đơn hàng', 'Xác nhận hoàn thành đơn hàng, tính hoa hồng và hoàn tiền theo tỷ lệ quy định.', 10, NOW()),
('App - Đặt Sản Phẩm', 'Đánh giá sản phẩm thành công', 'Đánh giá sản phẩm với số sao và nội dung, hiển thị thông báo "Đánh giá thành công" và đánh giá xuất hiện trên chi tiết sản phẩm.', 10, NOW()),
('App - Đặt Sản Phẩm', 'Kiểm tra xác thực trống khi đánh giá', 'Nhấn gửi đánh giá mà không nhập dữ liệu, hiển thị thông báo "Không được để trống".', 10, NOW()),
('App - Thông Tin Tài Khoản', 'Thay đổi thông tin tài khoản thành công', 'Cập nhật thông tin cá nhân (Tên, Số điện thoại, Email, CCCD), hiển thị thông báo "Cập nhật thông tin thành công".', 10, NOW()),
('App - Thông Tin Tài Khoản', 'Kiểm tra xác thực trống khi cập nhật tài khoản', 'Nhấn "Cập nhật" mà không nhập trường bắt buộc, hiển thị thông báo yêu cầu điền thông tin.', 10, NOW()),
('App - Thông Tin Tài Khoản', 'Thay đổi ảnh đại diện thành công', 'Thay đổi ảnh đại diện, hình ảnh được cập nhật thành công.', 10, NOW()),
('App - Affiliate', 'Hiển thị chi tiết Affiliate', 'Xem chi tiết Affiliate, hiển thị đầy đủ thông tin mã Affiliate.', 10, NOW()),
('App - Quản Lý QRCode', 'Tải QRCode thành công', 'Tải QRCode cá nhân xuống máy.', 10, NOW()),
('App - Quản Lý QRCode', 'Chia sẻ QRCode thành công', 'Chia sẻ QRCode qua ứng dụng, QRCode được gửi thành công.', 10, NOW()),
('App - Quản Lý QRCode', 'Quét QRCode để lấy mã giới thiệu', 'Quét QRCode cá nhân, hiển thị tên và mã người giới thiệu.', 10, NOW()),
('App - Yêu Cầu Hỗ Trợ', 'Tạo yêu cầu hỗ trợ thành công', 'Tạo yêu cầu hỗ trợ với thông tin hợp lệ, hiển thị thông báo "Tạo yêu cầu hỗ trợ thành công".', 10, NOW())
('App - Yêu Cầu Hỗ Trợ', 'Kiểm tra xác thực trống', 'Nhấn gửi yêu cầu hỗ trợ mà không nhập dữ liệu, hiển thị thông báo yêu cầu điền thông tin.', 10, NOW());