-- Insert all CMS test cases from user-provided list
INSERT INTO test_cases (hang_muc, tinh_nang, mo_ta, so_lan_phai_test, created_at) VALUES
('CMS - Đăng Nhập', 'Đăng nhập thành công với trường bắt buộc', 'Đăng nhập với Email/Số điện thoại và Mật khẩu hợp lệ, hiển thị thông báo "Đăng nhập thành công".', 10, NOW()),
('CMS - Đăng Nhập', 'Kiểm tra xác thực dữ liệu trống', 'Nhấn "Đăng nhập" mà không nhập dữ liệu, hiển thị thông báo "Bắt buộc" màu đỏ.', 10, NOW()),
('CMS - Đăng Nhập', 'Đăng nhập không thành công với Email/Số điện thoại không có giá trị', 'Đăng nhập với Email/Số điện thoại trống, hiển thị thông báo "Không hợp lệ" màu đỏ.', 10, NOW()),
('CMS - Đăng Nhập', 'Đăng nhập không thành công với mật khẩu không có giá trị', 'Đăng nhập với Email/Số điện thoại hợp lệ nhưng mật khẩu trống, hiển thị thông báo "Không hợp lệ" màu đỏ.', 10, NOW()),
('CMS - Đăng Nhập', 'Đăng nhập không thành công với tài khoản không có quyền truy cập', 'Đăng nhập với tài khoản khách hàng không có quyền, hiển thị thông báo "Không hợp lệ" màu đỏ.', 10, NOW()),
('CMS - Hệ Thống Affiliate - Người Dùng', 'Thêm mới người dùng thành công', 'Thêm người dùng với thông tin hợp lệ, hiển thị thông báo "Thêm thành công" và gửi email cho khách hàng.', 10, NOW()),
('CMS - Hệ Thống Affiliate - Người Dùng', 'Kiểm tra xác thực trống khi thêm người dùng', 'Nhấn "Lưu" mà không nhập dữ liệu, hiển thị thông báo "Trường bắt buộc".', 10, NOW()),
('CMS - Hệ Thống Affiliate - Người Dùng', 'Thêm mới người dùng với mã giới thiệu thành công', 'Thêm người dùng với mã giới thiệu hợp lệ, hiển thị thông báo "Thêm thành công", gửi email cho khách hàng và người giới thiệu.', 10, NOW()),
('CMS - Hệ Thống Affiliate - Người Dùng', 'Khóa tài khoản vĩnh viễn thành công', 'Khóa tài khoản vĩnh viễn với lý do, gửi email cho khách hàng và hạn chế truy cập.', 10, NOW()),
('CMS - Hệ Thống Affiliate - Người Dùng', 'Khóa tài khoản tạm thời thành công', 'Khóa tài khoản tạm thời với lý do và thời gian, hiển thị thông báo và hạn chế truy cập trên app.', 10, NOW()),
('CMS - Hệ Thống Affiliate - Người Dùng', 'Kiểm tra xác thực trống khi khóa tài khoản', 'Nhấn "Khóa tài khoản" mà không nhập dữ liệu, hiển thị thông báo "Bắt buộc" màu đỏ.', 10, NOW()),
('CMS - Hệ Thống Affiliate - Người Dùng', 'Kích hoạt tài khoản thành công', 'Kích hoạt tài khoản, hiển thị thông báo xác nhận trạng thái hoạt động.', 10, NOW()),
('CMS - Hệ Thống Affiliate - Người Dùng', 'Tự động mở khóa tài khoản tạm thời', 'Sau thời gian quy định, hệ thống tự động mở khóa tài khoản và gửi email cho khách hàng.', 10, NOW()),
('CMS - Hệ Thống Affiliate - Người Dùng', 'Cập nhật người dùng thành công', 'Cập nhật thông tin người dùng, hiển thị thông báo "Cập nhật thành công".', 10, NOW()),
('CMS - Hệ Thống Affiliate - Người Dùng', 'Xác thực mã giới thiệu sai', 'Thêm người dùng với mã giới thiệu không tồn tại, hiển thị thông báo "Không tìm thấy người dùng".', 10, NOW()),
('CMS - Hệ Thống Affiliate - Người Dùng', 'Cấp lại mật khẩu ngẫu nhiên thành công', 'Cấp lại mật khẩu ngẫu nhiên, hiển thị thông báo "Cấp lại mật khẩu thành công" và gửi email cho khách hàng.', 10, NOW()),
('CMS - Hệ Thống Affiliate - Phê Duyệt Nạp/Rút', 'Kiểm tra xác thực trống khi phê duyệt/từ chối', 'Nhấn "Từ chối/Phê duyệt" mà không chọn giao dịch, hiển thị thông báo "Bắt buộc" màu đỏ.', 10, NOW()),
('CMS - Hệ Thống Affiliate - Phê Duyệt Nạp/Rút', 'Phê duyệt yêu cầu nạp/rút thành công', 'Phê duyệt phiếu nạp/rút, hiển thị thông báo thành công và cập nhật tiền vào/ra tài khoản.', 10, NOW()),
('CMS - Hệ Thống Affiliate - Phê Duyệt Nạp/Rút', 'Tìm kiếm phiếu nạp/rút thành công', 'Tìm kiếm phiếu với tên người dùng hợp lệ, hiển thị danh sách phiếu tương ứng.', 10, NOW()),
('CMS - Hệ Thống Affiliate - Phê Duyệt Nạp/Rút', 'Từ chối yêu cầu nạp/rút thành công', 'Từ chối phiếu nạp/rút, hiển thị thông báo thành công và không cập nhật tiền vào/ra tài khoản.', 10, NOW()),
('CMS - Phiếu Nạp', 'Tạo phiếu nạp tiền thành công', 'Tạo phiếu nạp với thông tin hợp lệ, hiển thị thông báo "Tạo phiếu nạp thành công" và trạng thái "Chờ duyệt".', 10, NOW()),
('CMS - Phiếu Nạp', 'Kiểm tra xác thực trống', 'Nhấn "Tạo" mà không nhập dữ liệu, hiển thị thông báo "Trường bắt buộc".', 10, NOW()),
('CMS - Phiếu Nạp', 'Tạo phiếu nạp không thành công với số tiền nhỏ hơn tối thiểu', 'Tạo phiếu nạp với số tiền nhỏ hơn tối thiểu, hiển thị thông báo "Số tiền nạp tối thiểu là X".', 10, NOW()),
('CMS - Phiếu Rút', 'Tạo phiếu rút tiền thành công', 'Tạo phiếu rút với thông tin hợp lệ, hiển thị thông báo "Tạo phiếu rút thành công" và trạng thái "Chờ duyệt".', 10, NOW()),
('CMS - Phiếu Rút', 'Kiểm tra xác thực trống', 'Nhấn "Tạo" mà không nhập dữ liệu, hiển thị thông báo "Trường bắt buộc".', 10, NOW()),
('CMS - Phiếu Rút', 'Tạo phiếu rút không thành công với số tiền nhỏ hơn tối thiểu', 'Tạo phiếu rút với số tiền nhỏ hơn tối thiểu, hiển thị thông báo "Số tiền rút tối thiểu là X".', 10, NOW()),
('CMS - Phiếu Rút', 'Tạo phiếu rút không thành công với số tiền lớn hơn tối đa', 'Tạo phiếu rút với số tiền lớn hơn tối đa, hiển thị thông báo "Số tiền rút tối đa là X".', 10, NOW()),
('CMS - Phiếu Rút', 'Tạo phiếu rút không thành công khi số tiền lớn hơn số dư', 'Tạo phiếu rút với số tiền vượt số dư, hiển thị thông báo "Số tiền rút không hợp lệ".', 10, NOW()),
('CMS - Phiếu Rút', 'Tạo phiếu rút không thành công khi thiếu số tài khoản', 'Tạo phiếu rút mà không nhập số tài khoản, hiển thị thông báo "Trường bắt buộc".', 10, NOW()),
('CMS - Lịch Sử Giao Dịch Nạp/Rút', 'Lọc giao dịch theo loại ví', 'Lọc lịch sử giao dịch theo loại ví APEC, hiển thị danh sách giao dịch tương ứng.', 10, NOW()),
('CMS - Lịch Sử Giao Dịch Nạp/Rút', 'Lọc giao dịch theo loại người dùng', 'Lọc lịch sử giao dịch theo người dùng, hiển thị danh sách giao dịch của người dùng được chọn.', 10, NOW()),
('CMS - Lịch Sử Giao Dịch Nạp/Rút', 'Hiển thị chi tiết giao dịch', 'Chọn mã giao dịch, hiển thị thông tin chi tiết giao dịch.', 10, NOW()),
('CMS - Lịch Sử Giao Dịch Nạp/Rút', 'Tải danh sách nạp/rút thành công', 'Tải xuống danh sách nạp/rút theo bộ lọc đã chọn.', 10, NOW()),
('CMS - Đơn Hàng', 'Hiển thị danh sách đơn hàng', 'Hiển thị danh sách các đơn hàng của hệ thống.', 10, NOW()),
('CMS - Chương Trình Khuyến Mãi', 'Thêm khuyến mãi thành công', 'Thêm khuyến mãi với thông tin hợp lệ, hiển thị thông báo thành công.', 10, NOW()),
('CMS - Chương Trình Khuyến Mãi', 'Kiểm tra xác thực trống khi tạo khuyến mãi', 'Nhấn "Lưu" mà không nhập dữ liệu, hiển thị thông báo "Đây là trường bắt buộc".', 10, NOW()),
('CMS - Chương Trình Khuyến Mãi', 'Chỉnh sửa khuyến mãi thành công', 'Cập nhật thông tin khuyến mãi, hiển thị thông báo thành công.', 10, NOW()),
('CMS - Chương Trình Khuyến Mãi', 'Xóa khuyến mãi thành công', 'Xóa khuyến mãi, hiển thị thông báo "Xóa thành công".', 10, NOW()),
('CMS - Chương Trình Khuyến Mãi', 'Lọc khuyến mãi theo loại/ngành hàng', 'Lọc khuyến mãi theo loại hoặc ngành hàng, hiển thị danh sách tương ứng.', 10, NOW()),
('CMS - Ngành Hàng', 'Thêm mới ngành hàng thành công', 'Thêm ngành hàng với tên hợp lệ, hiển thị thông báo "Thêm thành công".', 10, NOW()),
('CMS - Ngành Hàng', 'Kiểm tra xác thực trống khi thêm ngành hàng', 'Nhấn "Lưu" mà không nhập dữ liệu, hiển thị thông báo "Trường bắt buộc".', 10, NOW()),
('CMS - Ngành Hàng', 'Chỉnh sửa ngành hàng thành công', 'Cập nhật thông tin ngành hàng, hiển thị thông báo "Cập nhật thành công".', 10, NOW()),
('CMS - Ngành Hàng', 'Xóa ngành hàng thành công', 'Xóa ngành hàng, hiển thị thông báo "Xóa thành công".', 10, NOW()),
('CMS - Danh Mục Sản Phẩm', 'Thêm mới danh mục sản phẩm thành công', 'Thêm danh mục sản phẩm với thông tin hợp lệ, hiển thị thông báo "Thêm thành công".', 10, NOW()),
('CMS - Danh Mục Sản Phẩm', 'Kiểm tra xác thực trống khi thêm danh mục', 'Nhấn "Lưu" mà không nhập dữ liệu, hiển thị thông báo "Trường bắt buộc".', 10, NOW()),
('CMS - Danh Mục Sản Phẩm', 'Chỉnh sửa danh mục sản phẩm thành công', 'Cập nhật thông tin danh mục sản phẩm, hiển thị thông báo "Cập nhật thành công".', 10, NOW()),
('CMS - Danh Mục Sản Phẩm', 'Xóa danh mục sản phẩm thành công', 'Xóa danh mục sản phẩm, hiển thị thông báo "Xóa thành công".', 10, NOW()),
('CMS - Bài Viết - Danh Mục Bài Viết', 'Thêm mới danh mục bài viết thành công', 'Thêm danh mục bài viết với tên hợp lệ, hiển thị thông báo "Thêm mới thành công".', 10, NOW()),
('CMS - Bài Viết - Danh Mục Bài Viết', 'Kiểm tra xác thực trống khi thêm danh mục', 'Nhấn "Lưu" mà không nhập dữ liệu, hiển thị thông báo "Trường bắt buộc".', 10, NOW()),
('CMS - Bài Viết - Danh Mục Bài Viết', 'Chỉnh sửa danh mục bài viết thành công', 'Cập nhật thông tin danh mục bài viết, hiển thị thông báo "Cập nhật thành công".', 10, NOW()),
('CMS - Bài Viết - Danh Mục Bài Viết', 'Xóa danh mục bài viết thành công', 'Xóa danh mục bài viết, hiển thị thông báo "Xóa thành công".', 10, NOW()),
('CMS - Bài Viết', 'Thêm mới bài viết thành công', 'Thêm bài viết với thông tin hợp lệ, hiển thị thông báo "Thêm mới thành công".', 10, NOW()),
('CMS - Bài Viết', 'Kiểm tra xác thực trống khi thêm bài viết', 'Nhấn "Lưu" mà không nhập dữ liệu, hiển thị thông báo "Trường bắt buộc".', 10, NOW()),
('CMS - Bài Viết', 'Chỉnh sửa bài viết thành công', 'Cập nhật thông tin bài viết, hiển thị thông báo "Cập nhật thành công".', 10, NOW()),
('CMS - Bài Viết', 'Xóa bài viết thành công', 'Xóa bài viết, hiển thị thông báo "Xóa thành công".', 10, NOW()),
('CMS - Yêu Cầu Hỗ Trợ', 'Xử lý yêu cầu hỗ trợ thành công', 'Xử lý yêu cầu hỗ trợ, cập nhật trạng thái thành "Đang xử lý" và hiển thị thông báo thành công.', 10, NOW()),
('CMS - Yêu Cầu Hỗ Trợ', 'Hoàn thành yêu cầu hỗ trợ thành công', 'Hoàn thành yêu cầu hỗ trợ, cập nhật trạng thái thành "Đã xử lý" và hiển thị thông báo thành công.', 10, NOW()); 